### ISSUE TITLE
webpack加载字体

### ISSUE THREAD

**Issue by 253867843** [253867843/Web#102]
* css代码

```css
        @font-face {
          font-family: "MyFont";
          src: url("Sauce Code Powerline Light.otf");
          font-weight: 600;
          font-style: normal;
        }

        body {
          background: green;
        }

        .code {
          font-family: MyFont;
          font-size: 16px;
          color: #333;
        }
```

* webpack.config.js

```js
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name]-[hash:4].[ext]',
                            outputPath: 'fonts'
                        }
                    }
                ]
            } 
```
